# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://network-ai.github.io
title: Network.AI
email: network.artificial.intelligence@gmail.com
author: Network.AI
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2021 Network.AI All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/NetworkAI_
  - title: github
    url: https://github.com/network-ai/
  - title: linkedin
    url: https://www.linkedin.com/in/network-ai
